name: CI - Push to main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
    format:
      runs-on: ubuntu-latest
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      steps:
        - name: Check out code using Git
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            ref: ${{ github.head_ref }}
            token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}
  
        - name: Install Tools & Dependencies
          uses: ./.github/actions/install
  
        - name: Format code
          run: pnpm run lint:fix
  
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
          with:
            commit_message: '[ci] lint'
            branch: ${{ github.head_ref }}
            commit_user_name: studiocms-no-reply
            commit_user_email: no-reply@studiocms.dev
            commit_author: StudioCMS <no-reply@studiocms.dev>
            
    mergebot:
      if: ${{ github.repository_owner == 'withstudiocms' && github.event_name == 'push' && github.event.commits[0].message != '[ci] lint' && github.event.commits[0].author.username != 'dependabot[bot]' }}
      uses: withstudiocms/automations/.github/workflows/mergebot.yml@main
      secrets:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MERGEBOT }}